# app/config/routing.yml
app:
    resource: "@FormAlertBundle/Controller/"
    type:     annotation

user_register:
    path: /register
    defaults: { _controller: FormAlertBundle\Controller\RegistrationController::registerAction }

# app/config/routing.yml
formulaire_create:
    path:     /formulaire/create
    defaults: { _controller: FormAlertBundle:Formulaire:createFormulaire }

formulaire_success:
    path:     /formulaire/success/{code_formulaire}
    defaults: { _controller: FormAlertBundle:Formulaire:success }

# app/config/routing.yml
app_formulaire:
    resource: "@FormAlertBundle/Controller/"
    type:     annotation

creer_formulaire:
    path:     /creer-formulaire
    defaults: { _controller: FormAlertBundle:Formulaire:creerFormulaire }

afficher_formulaire:
    path:     /formulaire/{code}
    defaults: { _controller: FormAlertBundle:Formulaire:afficherFormulaire }
